/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.Test
import org.junit.Assert.*

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        assertTrue(true)
    }
}
